package com.model;

public enum Status 
{
	NEW,SAVED_EDITOR,REQUIRES_EDITOR_ATTENTION,
	SUBMITTED_TO_SENIOR_EDITOR	,SAVED_SENIOR_EDITOR,REQUIRES_SENIOR_EDITOR_ATTENTION,
	SUBMITTED_TO_REVIEWER,SAVED_REVIEWER,FROZEN,
	PUBLISHED
}
